### ISSUE TITLE
Can't compile in arch (64bit) (solved reverting to gcc 5.3, won't compile with gcc 6.1.1)

### ISSUE THREAD

**Issue by pedropatinho** [falkTX/Carla#395]
I'm trying to install carla-git from AUR and it fails with this error:

```
In file included from codecs/juce_FlacAudioFormat.cpp:78:0,
                 from juce_audio_formats.cpp:100:
codecs/flac/libFLAC/lpc_flac.c: In function ‘long int juce::FlacNamespace::lround(double)’:
codecs/flac/libFLAC/lpc_flac.c:60:39: error: ‘long int juce::FlacNamespace::lround(double)’ conflicts with a previous declaration
 static inline long int lround(double x) {
                                       ^
In file included from /usr/include/features.h:368:0,
                 from /usr/include/sched.h:22,
                 from ../juce_audio_basics/../juce_core/native/juce_BasicNativeHeaders.h:166,
                 from ../juce_audio_basics/../juce_core/juce_core.h:137,
                 from ../juce_audio_basics/juce_audio_basics.h:28,
                 from juce_audio_formats.h:28,
                 from juce_audio_formats.cpp:38:
/usr/include/bits/mathcalls.h:341:1: note: previous declaration ‘long int lround(double)’
 __MATHDECL (long int,lround,, (_Mdouble_ __x));
 ^
In file included from codecs/juce_FlacAudioFormat.cpp:78:0,
                 from juce_audio_formats.cpp:100:
codecs/flac/libFLAC/lpc_flac.c: In function ‘int juce::FlacNamespace::FLAC__lpc_quantize_coefficients(const FLAC__real*, unsigned int, unsigned int, juce::FlacNamespace::FLAC__int32*, int*)’:
codecs/flac/libFLAC/lpc_flac.c:213:20: error: call of overloaded ‘lround(juce::FlacNamespace::FLAC__double&)’ is ambiguous
    q = lround(error);
                    ^
In file included from ../juce_audio_basics/../juce_core/system/juce_StandardHeader.h:69:0,
                 from ../juce_audio_basics/../juce_core/juce_core.h:140,
                 from ../juce_audio_basics/juce_audio_basics.h:28,
                 from juce_audio_formats.h:28,
                 from juce_audio_formats.cpp:38:
/usr/include/c++/6.1.1/cmath:1594:3: note: candidate: constexpr long int std::lround(long double)
   lround(long double __x)
   ^~~~~~
In file included from /usr/include/features.h:368:0,
                 from /usr/include/sched.h:22,
                 from ../juce_audio_basics/../juce_core/native/juce_BasicNativeHeaders.h:166,
                 from ../juce_audio_basics/../juce_core/juce_core.h:137,
                 from ../juce_audio_basics/juce_audio_basics.h:28,
                 from juce_audio_formats.h:28,
                 from juce_audio_formats.cpp:38:
/usr/include/bits/mathcalls.h:341:1: note: candidate: long int lround(double)
 __MATHDECL (long int,lround,, (_Mdouble_ __x));
 ^
In file included from ../juce_audio_basics/../juce_core/system/juce_StandardHeader.h:69:0,
                 from ../juce_audio_basics/../juce_core/juce_core.h:140,
                 from ../juce_audio_basics/juce_audio_basics.h:28,
                 from juce_audio_formats.h:28,
                 from juce_audio_formats.cpp:38:
/usr/include/c++/6.1.1/cmath:1590:3: note: candidate: constexpr long int std::lround(float)
   lround(float __x)
   ^~~~~~
In file included from codecs/juce_FlacAudioFormat.cpp:78:0,
                 from juce_audio_formats.cpp:100:
codecs/flac/libFLAC/lpc_flac.c:60:24: note: candidate: long int juce::FlacNamespace::lround(double)
 static inline long int lround(double x) {
                        ^~~~~~
In file included from codecs/juce_FlacAudioFormat.cpp:78:0,
                 from juce_audio_formats.cpp:100:
codecs/flac/libFLAC/lpc_flac.c:242:20: error: call of overloaded ‘lround(juce::FlacNamespace::FLAC__double&)’ is ambiguous
    q = lround(error);
                    ^
In file included from ../juce_audio_basics/../juce_core/system/juce_StandardHeader.h:69:0,
                 from ../juce_audio_basics/../juce_core/juce_core.h:140,
                 from ../juce_audio_basics/juce_audio_basics.h:28,
                 from juce_audio_formats.h:28,
                 from juce_audio_formats.cpp:38:
/usr/include/c++/6.1.1/cmath:1594:3: note: candidate: constexpr long int std::lround(long double)
   lround(long double __x)
   ^~~~~~
In file included from /usr/include/features.h:368:0,
                 from /usr/include/sched.h:22,
                 from ../juce_audio_basics/../juce_core/native/juce_BasicNativeHeaders.h:166,
                 from ../juce_audio_basics/../juce_core/juce_core.h:137,
                 from ../juce_audio_basics/juce_audio_basics.h:28,
                 from juce_audio_formats.h:28,
                 from juce_audio_formats.cpp:38:
/usr/include/bits/mathcalls.h:341:1: note: candidate: long int lround(double)
 __MATHDECL (long int,lround,, (_Mdouble_ __x));
 ^
In file included from ../juce_audio_basics/../juce_core/system/juce_StandardHeader.h:69:0,
                 from ../juce_audio_basics/../juce_core/juce_core.h:140,
                 from ../juce_audio_basics/juce_audio_basics.h:28,
                 from juce_audio_formats.h:28,
                 from juce_audio_formats.cpp:38:
/usr/include/c++/6.1.1/cmath:1590:3: note: candidate: constexpr long int std::lround(float)
   lround(float __x)
   ^~~~~~
In file included from codecs/juce_FlacAudioFormat.cpp:78:0,
                 from juce_audio_formats.cpp:100:
codecs/flac/libFLAC/lpc_flac.c:60:24: note: candidate: long int juce::FlacNamespace::lround(double)
 static inline long int lround(double x) {
                        ^~~~~~

```
I have successfuly installed carla-git in another pc (same setup) some days ago, haven't a clue what is going on this time...

**Comment by SpotlightKid** [comment]
Probably caused by the switch of Arch to GCC 6.1, which breaks compilation of a lot of programs.

**Comment by pedropatinho** [comment]
I may have compiled the other one with the older gcc, though. I'll give a try to gcc 5 later today and post the results.

**Comment by pedropatinho** [comment]
Ok, seems like it was gcc 6.1.1. Just succeeded using gcc 5.3. Nevertheless, I think this "lround() conflicting declaration" could be removed...

I'm not great at C++, but I guess using the full namespace for the function would do it?

**Comment by xnakos** [comment]
I think the problem is that `#if !defined(HAVE_LROUND)` is true for both g++ 5 and 6 (see what happens when you use `pragma message` right after that line - also removing the static `lround` function below compiles perfectly, indicating that `lround` exists despite the `HAVE_LROUND` being undefined) but 5 happily uses the static function, although another conflicting declaration exists, while 6 complains. So it is a matter of correctly detecting the existence of `lround`.

**Comment by xnakos** [comment]
To provide some more insight, this is the result of `grep 'HAVE_LROUND' -r .` for the latest master of flac and JUCE respectively:

```
./src/libFLAC/lpc.c:#elif !defined(HAVE_LROUND) && defined(__GNUC__)
./build/config.mk:    CONFIG_CFLAGS += -DHAVE_LROUND
./configure.ac:AC_SEARCH_LIBS([lround],[m], [AC_DEFINE(HAVE_LROUND,1,lround support)])
```
(the first line is the common line among Carla, JUCE, flac, just refactored in the latest master)

```
./modules/juce_audio_formats/codecs/flac/libFLAC/lpc_flac.c:#if !defined(HAVE_LROUND)
```
(the one appearance that exists in Carla too)

For flac, autoconf takes care of the definition of `HAVE_LROUND`. I do not know how JUCE is built, but this definition is missing from there. That is why it is missing from Carla too.

Also, to fully cover the g++ front, http://c0x.coding-guidelines.com/6.2.2.html states that

> If, within a translation unit, the same identifier appears with both internal and external linkage, the behavior is undefined.

If I am not mistaken, regarding `lround`, including math.h indicates external linkage and subsequent static definition indicates internal linkage. GCC 5 handles the undefined behavior by allowing linking to the static function. GCC 6 handles the undefined behavior by throwing a compilation error.

My hard-earned two cents, having a case of javitis.

**Comment by falkTX** [comment]
This has been fixed already, forgot to close the bug.
