### ISSUE TITLE
Fails to build with clang-4.0.0

### ISSUE THREAD

**Issue by yurivict** [falkTX/Carla#503]
clang-4.0.0 gives these errors using this key -std=c++14:

```
/usr/include/c++/v1/type_traits:4213:1: error: illegal initializer (only variables can be initialized)
__invoke(_Fp&& __f, _A0&& __a0, _Args&& ...__args)
^
/usr/include/c++/v1/type_traits:4214:1: error: expected ';' at end of declaration
_LIBCPP_INVOKE_RETURN((_VSTD::forward<_A0>(__a0).*__f)(_VSTD::forward<_Args>(__args)...))
^
/usr/include/c++/v1/type_traits:4198:37: note: expanded from macro '_LIBCPP_INVOKE_RETURN'
    noexcept(noexcept(__VA_ARGS__)) -> decltype(__VA_ARGS__) \
                                    ^
/usr/include/c++/v1/type_traits:4214:1: error: cannot use arrow operator on a type
/usr/include/c++/v1/type_traits:4198:37: note: expanded from macro '_LIBCPP_INVOKE_RETURN'
    noexcept(noexcept(__VA_ARGS__)) -> decltype(__VA_ARGS__) \
                                    ^
```

carla-1.2.4

**Comment by falkTX** [comment]
carla 1.x is *old*
please use latest git.
also, use c++11 mode as set by the makefiles. there's no speed gains or improvements by changing the c++ version...

**Comment by yurivict** [comment]
The latest also fails:

```
In file included from ../../modules/juce_core/juce_core.h:261:
../../modules/juce_core/containers/juce_HashMap.h:52:98: error: cast from pointer to smaller type 'pointer_sized_uint' (aka 'unsigned int') loses information
    int generateHash (const void* key, const int upperLimit) const noexcept      { return (int)(((pointer_sized_uint) key) % ((pointer_sized_uint) upperLimit)); }
```

**Comment by yurivict** [comment]
Ok, that latest one is due to the FreeBSD not being detected in juice.

**Comment by falkTX** [comment]
again, don't build against v1.x of carla.
also, freebsd is not supported in juce right now, and thus not supported by carla at this point.

**Comment by yurivict** [comment]
Too bad you chose closed source, non-cross-platform framework Juce, and not Qt that works everywhere.
It encumbers Carla.

**Comment by falkTX** [comment]
the hell are you saying? juce is GPL, and it's cross-platform supporting Linux, MacOS and Windows.
I do not have a machine that runs FreeBSD, so even if carla compiles for it I would not be able to run it myself and actually support it.

And anyway, if you're really interested on FreeBSD, you can start patching Carla or Juce to support it.
Carla on Linux only uses the base non-gui side of Juce, so making it work would not be that hard for a developer.
Instead of complaining, you can fork Carla and do pull requests as needed to make it work on FreeBSD.

**Comment by yurivict** [comment]
> Instead of complaining, you can fork Carla and do pull requests as needed to make it work on FreeBSD.

I am not complaining. I tried to port it, and it requires extraordinary amount of work to make it work on the FreeBSD. This only indicates that Juce isn't nearly as portable as Qt
.

**Comment by falkTX** [comment]
the code is portable, Qt just has the work done already.
and as I said, carla on linux does not use a lot of juce stuff (and thus freebsd version would be the same)
See https://github.com/falkTX/Carla/blob/856bbf6015720cdccbe379508b0fd80606523d27/source/modules/AppConfig.h#L30
so only juce audio-basics, audio-formats and core need to have freebsd support.
since audio-basics and audio-formats have no platform-specific code, only juce-core needs some work.

**Comment by falkTX** [comment]
Note: I was able to build carla with clang-4.0 here in my linux installation, no more warnings now.
Building for FreeBSD is a different issue, please open a separate ticket for that.
I have interest to make things work there, but I will need some help setting up a VM for it.
Anyway, open a new bug report if you're willing to help get Carla working under FreeBSD.

**Comment by yurivict** [comment]
I think Juce not supporting FreeBSD is the main reason. Not much can be done until they support it. I've wrote this to their forums, and they answered that they are aware but this isn't apparently a priority.

**Comment by falkTX** [comment]
juce doesn't support lv2 either, but my fork does. ;)
freebsd on juce_core can be just the same.
I expect most things do not need to change, it's mostly just posix.

so create a new bug report if you're still interested on the topic.
I can do the freebsd base support in juce_core, and get carla to run.
but I'll leave all the testing and bug reporting to you.
