### ISSUE TITLE
Cannot compile with glibc ≥ 2.26 (__sigemptyset removed from its API)

### ISSUE THREAD

**Issue by waptaff** [falkTX/Carla#666]
Trying to compile 2.0-beta6 I get this error:

```
In file included from codecs/juce_FlacAudioFormat.cpp:136:0,
                 from juce_audio_formats.cpp:102:
codecs/flac/libFLAC/cpu.c: In function ‘void juce::FlacNamespace::FLAC__cpu_info(juce::FlacNamespace::FLAC__CPUInfo*)’:
codecs/flac/libFLAC/cpu.c:250:3: error: ‘__sigemptyset’ was not declared in this scope
   __sigemptyset(&sigill_sse.sa_mask);
   ^~~~~~~~~~~~~
codecs/flac/libFLAC/cpu.c:250:3: note: suggested alternative: ‘sigemptyset’
   __sigemptyset(&sigill_sse.sa_mask);
   ^~~~~~~~~~~~~
```

It appears `__sigemptyset` was removed in glibc, [in commit a992f506](https://sourceware.org/git/?p=glibc.git;a=commit;h=a992f506ff7162da2afa5a6151cc6f15949ceef4) (file `bits/sigset.h` was removed).

The fix probably just involves replacing the function call with `sigemptyset` (without the underscores) but I'll let the experts decide on a resolution.

**Comment by falkTX** [comment]
congrats on reaching bug #666 but this one is invalid.
carla does not use juce anymore, the build failure you have belongs to a code that carla no longer contains.
